---
region: "eu-west-2"
component: "alertmanager"

private_network_cidr: "10.0.0.0/16"

storage_bucket_name: "infrablocks-%{hiera('component')}-%{deployment_identifier}"
secrets_bucket_name: "%{hiera('storage_bucket_name')}"

domain_state_key: "domain/deployments/%{deployment_identifier}.tfstate"
domain_state_bucket_name: "%{hiera('storage_bucket_name')}"
domain_state_bucket_region: "%{hiera('region')}"
domain_state_bucket_is_encrypted: "true"

certificate_state_key: "certificate/deployments/%{deployment_identifier}.tfstate"
certificate_state_bucket_name: "%{hiera('storage_bucket_name')}"
certificate_state_bucket_region: "%{hiera('region')}"
certificate_state_bucket_is_encrypted: "true"

network_state_key: "network/deployments/%{deployment_identifier}.tfstate"
network_state_bucket_name: "%{hiera('storage_bucket_name')}"
network_state_bucket_region: "%{hiera('region')}"
network_state_bucket_is_encrypted: "true"

cluster_state_key: "cluster/deployments/%{deployment_identifier}.tfstate"
cluster_state_bucket_name: "%{hiera('storage_bucket_name')}"
cluster_state_bucket_region: "%{hiera('region')}"
cluster_state_bucket_is_encrypted: "true"

load_balancer_state_key: "load-balancer/deployments/%{deployment_identifier}.tfstate"
load_balancer_state_bucket_name: "%{hiera('storage_bucket_name')}"
load_balancer_state_bucket_region: "%{hiera('region')}"
load_balancer_state_bucket_is_encrypted: "true"

service_registry_state_key: "service-registry/deployments/%{deployment_identifier}.tfstate"
service_registry_state_bucket_name: "%{hiera('storage_bucket_name')}"
service_registry_state_bucket_region: "%{hiera('region')}"
service_registry_state_bucket_is_encrypted: "true"

service_state_key: "service/deployments/%{hiera('instance')}.tfstate"
service_state_bucket_name: "%{hiera('storage_bucket_name')}"
service_state_bucket_region: "%{hiera('region')}"
service_state_bucket_is_encrypted: "true"

configuration_state_key: "configuration/deployments/%{deployment_identifier}.tfstate"
configuration_state_bucket_name: "%{hiera('storage_bucket_name')}"
configuration_state_bucket_region: "%{hiera('region')}"
configuration_state_bucket_is_encrypted: "true"
