---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{deployment_identifier}"

  private_network_cidr: "%{hiera('private_network_cidr')}"

  domain_name: "%{hiera('domain_name')}"

  alertmanager_service_container_web_port: "9093"
  alertmanager_service_host_web_port: "9093"
  alertmanager_allow_cidrs:
    - "0.0.0.0/0"

  domain_state_key: "%{hiera('domain_state_key')}"
  domain_state_bucket_name: "%{hiera('domain_state_bucket_name')}"
  domain_state_bucket_region: "%{hiera('domain_state_bucket_region')}"

  network_state_key: "%{hiera('network_state_key')}"
  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"

backend_config:
  key: "%{hiera('load_balancer_state_key')}"
  bucket: "%{hiera('load_balancer_state_bucket_name')}"
  region: "%{hiera('load_balancer_state_bucket_region')}"
  encrypt: "%{hiera('load_balancer_state_bucket_is_encrypted')}"
