---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{deployment_identifier}"

  domain_name: "%{hiera('domain_name')}"

  instance: "%{hiera('instance')}"
  cluster_size: 3

  service_name: "%{hiera('component')}"
  service_registry_namespace: "%{hiera('component')}-%{deployment_identifier}-sd"
  service_desired_count: 1

  secrets_bucket_name: "%{hiera('secrets_bucket_name')}"

  alertmanager_image: "infrablocks/alertmanager-aws:0.5.0"
  alertmanager_service_container_web_port: "9093"
  alertmanager_service_host_web_port: "9093"
  alertmanager_service_container_cluster_port: "9094"
  alertmanager_service_host_cluster_port: "9094"
  alertmanager_storage_location: "/var/opt/alertmanager"
  alertmanager_allow_cidrs:
    - "0.0.0.0/0"

  domain_state_key: "%{hiera('domain_state_key')}"
  domain_state_bucket_name: "%{hiera('domain_state_bucket_name')}"
  domain_state_bucket_region: "%{hiera('domain_state_bucket_region')}"

  network_state_key: "%{hiera('network_state_key')}"
  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"

  load_balancer_state_key: "%{hiera('load_balancer_state_key')}"
  load_balancer_state_bucket_name: "%{hiera('load_balancer_state_bucket_name')}"
  load_balancer_state_bucket_region: "%{hiera('load_balancer_state_bucket_region')}"

  service_registry_state_key: "%{hiera('service_registry_state_key')}"
  service_registry_state_bucket_name: "%{hiera('service_registry_state_bucket_name')}"
  service_registry_state_bucket_region: "%{hiera('service_registry_state_bucket_region')}"

  cluster_state_key: "%{hiera('cluster_state_key')}"
  cluster_state_bucket_name: "%{hiera('cluster_state_bucket_name')}"
  cluster_state_bucket_region: "%{hiera('cluster_state_bucket_region')}"

backend_config:
  key: "%{hiera('service_state_key')}"
  bucket: "%{hiera('service_state_bucket_name')}"
  region: "%{hiera('service_state_bucket_region')}"
  encrypt: "%{hiera('service_state_bucket_is_encrypted')}"
