---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{deployment_identifier}"

  domain_name: "%{hiera('domain_name')}"

  domain_state_key: "%{hiera('domain_state_key')}"
  domain_state_bucket_name: "%{hiera('domain_state_bucket_name')}"
  domain_state_bucket_region: "%{hiera('domain_state_bucket_region')}"

  network_state_key: "%{hiera('network_state_key')}"
  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"

backend_config:
  key: "%{hiera('service_registry_state_key')}"
  bucket: "%{hiera('service_registry_state_bucket_name')}"
  region: "%{hiera('service_registry_state_bucket_region')}"
  encrypt: "%{hiera('service_registry_state_bucket_is_encrypted')}"
